name: Testing

on:
  pull_request_target:
    branches: [master]

jobs:
  test:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest
    environment: Testing    
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip tox
      - name: Patch utils.config to use github env secrets
        run: cd utils && patch < ../tests/gh-actions.patch
      - name: Test with coverage
        env:
          ARBITRUM_ENDPOINT: ${{ secrets.ARBITRUM_ENDPOINT }}
          AVALANCHE_ENDPOINT: ${{ secrets.AVALANCHE_ENDPOINT }}
          BINANCE_ENDPOINT: ${{ secrets.BINANCE_ENDPOINT }}
          FANTOM_ENDPOINT: ${{ secrets.FANTOM_ENDPOINT }}
          IPFS_GATEWAY: ${{ secrets.IPFS_GATEWAY }}
          MORALIS_API_KEY: ${{ secrets.MORALIS_API_KEY }}
          OPENSEA_API_KEY: ${{ secrets.OPENSEA_API_KEY }}
          OPTIMISM_ENDPOINT: ${{ secrets.OPTIMISM_ENDPOINT }}
          POLYGON_ENDPOINT: ${{ secrets.POLYGON_ENDPOINT }}
          WEB3_PROVIDER: ${{ secrets.WEB3_PROVIDER }}
        run: |
          tox
