name: Testing

on: [push, pull_request]

jobs:
  test:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Create temporary .env
        run: echo -e "etherscan_API_KEY=${{secrets.ETHERSCAN_API_KEY}}\nweb3_provider=${{ secrets.WEB3_PROVIDER }}\narbitrum_web3_provider=${{ secrets.ARBITRUM_ENDPOINT }}\navalanche_web3_provider=${{ secrets.AVALANCHE_ENDPOINT }}\nfantom_web3_provider=${{ secrets.FANTOM_ENDPOINT }}\noptimism_web3_provider=${{ secrets.OPTIMISM_ENDPOINT }}\npolygon_web3_provider=${{ secrets.POLYGON_ENDPOINT }}\nbinance_web3_provider=${{secrets.BINANCE_ENDPOINT}}\nipfs_gateway=https://dweb.link/ipfs/" > .env
      - name: Test with coverage
        run: |
          tox
      - name: Delete temporary .env
        run: rm .env
